---
server:
  port: ${PORT:${SERVER_PORT:0}}
words: fallback

---
spring:
  profiles: sentence
server:
  port: 8020  
words: NotApplicable


---
spring:
  profiles: client
server:
  port: 8030
words: NotApplicable

---
spring:
  profiles: ajax
server:
  port: 8080
words: NotApplicable

---
# Zuul-proxied services can be found by calling /services/subject, /services/verb, etc. 
zuul:
  prefix: /services 

--- 
# Allow thymeleaf template changes to reload: 
spring.thymeleaf.cache: false 

